version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:latest
    container_name: kotacom-cms-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: kotacom-cms
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - cms-network

  # CMS Application
  cms-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: kotacom-cms-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URI=mongodb://admin:password@mongodb:27017/kotacom-cms?authSource=admin
      - PAYLOAD_SECRET=your-dev-secret-key
      - NEXT_PUBLIC_SERVER_URL=http://localhost:3000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - cms-network
    command: pnpm dev

  # MongoDB Express (Optional - for database management)
  mongo-express:
    image: mongo-express:latest
    container_name: kotacom-cms-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    depends_on:
      - mongodb
    networks:
      - cms-network

volumes:
  mongodb_data:

networks:
  cms-network:
    driver: bridge
